using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using GameFlow.Internal;
using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

namespace GameFlow.Editor
{
    public static class CoreContentUI
    {
        private static readonly Dictionary<UnityEngine.Object, UnityEditor.Editor> s_cachedEditors = new Dictionary<UnityEngine.Object, UnityEditor.Editor>();

        public static void RegisterCoreContent(VisualElement coreRoot, SerializedProperty autoGenerateProperty, SerializedProperty autoGenerateDataProperty)
        {
            if (coreRoot == null || autoGenerateProperty == null || autoGenerateDataProperty == null) return;

            var imguiContainer = new IMGUIContainer(() => OnGUIHandler(autoGenerateProperty, autoGenerateDataProperty));
            imguiContainer.style.flexGrow = 1;
            imguiContainer.style.marginTop = 10;

            imguiContainer.RegisterCallback<DetachFromPanelEvent>(_ => ClearAllCachedEditors());

            coreRoot.Add(imguiContainer);
        }

        private static void OnGUIHandler(SerializedProperty autoGenerateProp, SerializedProperty dataProp)
        {
            if (autoGenerateProp == null || dataProp == null) return;

            var serializedObject = autoGenerateProp.serializedObject;
            serializedObject.Update();

            var headerStyle = new GUIStyle(EditorStyles.boldLabel) { fontSize = 13, margin = new RectOffset(0, 0, 5, 5) };
            var groupStyle = new GUIStyle(EditorStyles.helpBox) { padding = new RectOffset(10, 10, 10, 10), margin = new RectOffset(0, 0, 10, 15) };
            var itemStyle = new GUIStyle(EditorStyles.helpBox) { padding = new RectOffset(5, 5, 5, 5), margin = new RectOffset(0, 0, 5, 5) };

            autoGenerateProp.boolValue = EditorGUILayout.ToggleLeft(new GUIContent("Auto Generate"), autoGenerateProp.boolValue);

            if (!autoGenerateProp.boolValue)
            {
                EditorGUILayout.Space(5);
                EditorGUILayout.HelpBox("Manual initialization required. Please initialize Runtime Controller manually at runtime.", MessageType.Warning);
            }
            else
            {
                var camerasProp = dataProp.FindPropertyRelative("Cameras");

                var shieldProp = dataProp.FindPropertyRelative("ShieldType");
                var loadingsProp = dataProp.FindPropertyRelative("Loadings");

                EditorGUILayout.BeginVertical(groupStyle);
                EditorGUILayout.LabelField("Cameras", headerStyle);
                DrawCamerasGroup(camerasProp, itemStyle);
                EditorGUILayout.EndVertical();

                EditorGUILayout.BeginVertical(groupStyle);
                EditorGUILayout.LabelField("Shield", headerStyle);

                if (shieldProp != null)
                {
                    EditorGUILayout.PropertyField(shieldProp, new GUIContent("Global Shield Type"));
                    GUILayout.Space(10);
                }
                else
                {
                    EditorGUILayout.HelpBox("Cannot find 'ShieldType'. Check [SerializeField] and variable name.", MessageType.Error);
                }

                EditorGUILayout.LabelField("Loadings", headerStyle);
                DrawLoadingsGroup(loadingsProp, itemStyle);
                EditorGUILayout.EndVertical();
            }

            serializedObject.ApplyModifiedProperties();
        }

        private static void DrawCamerasGroup(SerializedProperty camerasProp, GUIStyle itemStyle)
        {
            if (camerasProp == null) return;

            var presetIcon = EditorGUIUtility.IconContent("d_SettingsIcon");
            presetIcon.tooltip = "Apply Preset";

            var deleteIcon = EditorGUIUtility.IconContent("Toolbar Minus");
            deleteIcon.tooltip = "Remove Camera";

            for (var i = 0; i < camerasProp.arraySize; i++)
            {
                var elementProp = camerasProp.GetArrayElementAtIndex(i);
                var isMainProp = elementProp.FindPropertyRelative("IsMainUICamera");
                var camProp = elementProp.FindPropertyRelative("CameraPrefab");

                EditorGUILayout.BeginVertical(itemStyle);
                EditorGUILayout.BeginHorizontal();

                var oldColor = GUI.backgroundColor;
                if (isMainProp.boolValue) GUI.backgroundColor = new Color(0.2f, 0.6f, 0.2f, 1f);

                EditorGUI.BeginChangeCheck();
                var isMain = GUILayout.Toggle(isMainProp.boolValue, new GUIContent("", "Main UI Camera"), GUILayout.Width(16));
                if (EditorGUI.EndChangeCheck())
                {
                    if (isMain)
                    {
                        for (var j = 0; j < camerasProp.arraySize; j++)
                        {
                            camerasProp.GetArrayElementAtIndex(j).FindPropertyRelative("IsMainUICamera").boolValue = (j == i);
                        }
                    }
                    else
                    {
                        isMainProp.boolValue = false;
                    }
                }

                GUI.backgroundColor = oldColor;

                var hasCamera = camProp.objectReferenceValue != null;
                EditorGUI.BeginDisabledGroup(!hasCamera);
                if (GUILayout.Button(new GUIContent("Edit", "Toggle Camera Properties"), EditorStyles.miniButton, GUILayout.Width(40)))
                {
                    elementProp.isExpanded = !elementProp.isExpanded;
                }

                EditorGUI.EndDisabledGroup();

                var prevFieldColor = GUI.backgroundColor;
                if (!hasCamera) GUI.backgroundColor = new Color(1f, 0.35f, 0.35f, 1f);

                EditorGUILayout.PropertyField(camProp, GUIContent.none);

                GUI.backgroundColor = prevFieldColor;

                if (GUILayout.Button(presetIcon, EditorStyles.label, GUILayout.Width(22), GUILayout.Height(18)))
                {
                    ShowPresetMenu(camProp);
                }

                if (GUILayout.Button(deleteIcon, EditorStyles.label, GUILayout.Width(22), GUILayout.Height(18)))
                {
                    CleanUpEditor(camProp.objectReferenceValue);

                    camerasProp.DeleteArrayElementAtIndex(i);
                    EditorGUILayout.EndHorizontal();
                    EditorGUILayout.EndVertical();
                    break;
                }

                EditorGUILayout.EndHorizontal();

                if (hasCamera && elementProp.isExpanded)
                {
                    var nestedStyle = new GUIStyle(EditorStyles.helpBox) { margin = new RectOffset(20, 0, 5, 5), padding = new RectOffset(10, 5, 5, 5) };
                    EditorGUILayout.BeginVertical(nestedStyle);

                    EditorGUI.indentLevel++;
                    DrawCachedEditor(camProp.objectReferenceValue);
                    EditorGUI.indentLevel--;

                    EditorGUILayout.EndVertical();
                }

                EditorGUILayout.EndVertical();
            }

            EditorGUILayout.BeginHorizontal();
            GUILayout.FlexibleSpace();
            if (GUILayout.Button("+ Add Camera", EditorStyles.miniButton, GUILayout.Width(100)))
            {
                camerasProp.arraySize++;
            }

            EditorGUILayout.EndHorizontal();
        }

        private static void DrawLoadingsGroup(SerializedProperty loadingsProp, GUIStyle itemStyle)
        {
            if (loadingsProp == null) return;

            var deleteIcon = EditorGUIUtility.IconContent("Toolbar Minus");
            deleteIcon.tooltip = "Remove Loading";

            for (var i = 0; i < loadingsProp.arraySize; i++)
            {
                var elementProp = loadingsProp.GetArrayElementAtIndex(i);

                var hasController = elementProp.objectReferenceValue != null;
                BaseLoadingTypeController controller = null;
                SerializedObject innerSo = null;
                SerializedProperty idProp = null;

                if (hasController)
                {
                    controller = elementProp.objectReferenceValue as BaseLoadingTypeController;
                    innerSo = new SerializedObject(controller);
                    innerSo.Update();
                    idProp = innerSo.FindProperty("m_Id");
                }

                EditorGUILayout.BeginVertical(itemStyle);
                EditorGUILayout.BeginHorizontal();

                EditorGUILayout.LabelField($"{i}.", EditorStyles.centeredGreyMiniLabel, GUILayout.Width(20));

                if (idProp != null)
                {
                    EditorGUILayout.PropertyField(idProp, GUIContent.none, GUILayout.Width(100));
                }
                else
                {
                    GUILayout.Space(104);
                }

                EditorGUI.BeginDisabledGroup(!hasController);
                elementProp.isExpanded = GUILayout.Toggle(elementProp.isExpanded, new GUIContent("Edit", "Toggle Controller Properties"), EditorStyles.miniButton,
                    GUILayout.Width(40));
                EditorGUI.EndDisabledGroup();

                var prevFieldColor = GUI.backgroundColor;
                if (!hasController)
                {
                    GUI.backgroundColor = new Color(1f, 0.35f, 0.35f, 1f);
                }

                EditorGUILayout.PropertyField(elementProp, GUIContent.none);
                GUI.backgroundColor = prevFieldColor;

                if (GUILayout.Button(deleteIcon, EditorStyles.label, GUILayout.Width(22), GUILayout.Height(18)))
                {
                    CleanUpEditor(elementProp.objectReferenceValue);

                    loadingsProp.DeleteArrayElementAtIndex(i);
                    EditorGUILayout.EndHorizontal();
                    EditorGUILayout.EndVertical();
                    break;
                }

                EditorGUILayout.EndHorizontal();

                if (innerSo != null)
                {
                    innerSo.ApplyModifiedProperties();
                }

                if (hasController && elementProp.isExpanded)
                {
                    var nestedStyle = new GUIStyle(EditorStyles.helpBox) { margin = new RectOffset(20, 0, 5, 5), padding = new RectOffset(10, 5, 5, 5) };
                    EditorGUILayout.BeginVertical(nestedStyle);

                    EditorGUI.indentLevel++;
                    DrawCachedEditor(controller, true);
                    EditorGUI.indentLevel--;

                    EditorGUILayout.EndVertical();
                }

                EditorGUILayout.EndVertical();
            }

            EditorGUILayout.BeginHorizontal();
            GUILayout.FlexibleSpace();
            if (GUILayout.Button("+ Add Loading", EditorStyles.miniButton, GUILayout.Width(100)))
            {
                loadingsProp.arraySize++;
            }

            EditorGUILayout.EndHorizontal();
        }

        private static void ShowPresetMenu(SerializedProperty camProp)
        {
            var cam = camProp.objectReferenceValue as Camera;
            if (cam == null)
            {
                EditorUtility.DisplayDialog("Notice", "Please assign a Camera first.", "OK");
                return;
            }

            var menu = new GenericMenu();
            var presetTypes = TypeCache.GetTypesDerivedFrom<PresetCamera>().Where(t => !t.IsAbstract).ToList();

            foreach (var type in presetTypes)
            {
                var cleanName = type.Name.EndsWith("Preset") ? type.Name.Substring(0, type.Name.Length - 6) : type.Name;
                cleanName = Regex.Replace(cleanName, "([a-z])([A-Z])", "$1 $2");

                menu.AddItem(new GUIContent(cleanName), false, () =>
                {
                    Undo.RecordObject(cam, $"Apply {cleanName} Preset");
                    var presetInstance = Activator.CreateInstance(type) as PresetCamera;
                    presetInstance?.Preset(cam);
                    EditorUtility.SetDirty(cam);
                });
            }

            menu.ShowAsContext();
        }

        private static void DrawCachedEditor(UnityEngine.Object obj, bool hideScriptField = false)
        {
            if (obj == null) return;

            if (!s_cachedEditors.TryGetValue(obj, out UnityEditor.Editor editor) || editor == null)
            {
                editor = UnityEditor.Editor.CreateEditor(obj);
                s_cachedEditors[obj] = editor;
            }

            editor.serializedObject.Update();

            if (hideScriptField)
            {
                var prop = editor.serializedObject.GetIterator();
                if (prop.NextVisible(true))
                {
                    do
                    {
                        if (prop.name == "m_Script") continue;
                        if (prop.name == "m_Id") continue;
                        EditorGUILayout.PropertyField(prop, true);
                    } while (prop.NextVisible(false));
                }
            }
            else
            {
                editor.OnInspectorGUI();
            }

            editor.serializedObject.ApplyModifiedProperties();
        }

        public static void CleanUpEditor(UnityEngine.Object obj)
        {
            if (obj == null || !s_cachedEditors.TryGetValue(obj, out var editor)) return;
            if (editor != null) UnityEngine.Object.DestroyImmediate(editor);
            s_cachedEditors.Remove(obj);
        }

        public static void ClearAllCachedEditors()
        {
            foreach (var editor in s_cachedEditors.Values.Where(editor => editor != null))
            {
                UnityEngine.Object.DestroyImmediate(editor);
            }

            s_cachedEditors.Clear();
        }
    }
}